# Generated by Django 3.2.9 on 2021-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('upload_id', models.BigIntegerField()),
                ('type', models.CharField(default='', max_length=50)),
                ('distance', models.FloatField(default=0)),
                ('moving_time', models.FloatField(default=0)),
                ('average_speed', models.FloatField(default=0)),
                ('max_speed', models.FloatField(default=0)),
                ('total_elevation_gain', models.FloatField(default=0)),
                ('start_date_local', models.DateField()),
                ('start_time_local', models.DateTimeField()),
            ],
        ),
    ]
