# Generated by Django 3.2.9 on 2021-12-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_heartrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='average_watts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='elev_high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='elev_low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='has_heartrate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='kilojoules',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_heartrate',
            field=models.FloatField(default=0),
        ),
    ]
