# Generated by Django 3.2.9 on 2021-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_max_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='extern_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
