# Generated by Django 3.2.9 on 2021-12-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_extern_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_watts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kilojoules',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_watts',
            field=models.FloatField(null=True),
        ),
    ]
