# Generated by Django 3.2.9 on 2021-12-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20211215_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='start_time_local',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date_local',
        ),
        migrations.AddField(
            model_name='activity',
            name='timezone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='utc_offset',
            field=models.IntegerField(default=0),
        ),
    ]
